// <auto-generated />
using System;
using InitialProject.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InitialProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230417111133_nestonovo")]
    partial class nestonovo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("InitialProject.Model.Accomodation", b =>
                {
                    b.Property<int>("AccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccomodationReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccomodationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysBeforeCanceling")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GuestUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinReservationDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccId");

                    b.HasIndex("AccomodationReservationId");

                    b.HasIndex("GuestUserId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Accomodations");
                });

            modelBuilder.Entity("InitialProject.Model.AccomodationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccomodationAccId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationAccId");

                    b.ToTable("AccomodationImages");
                });

            modelBuilder.Entity("InitialProject.Model.AccomodationReservation", b =>
                {
                    b.Property<int>("AccomodationReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccomodationAccId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuestUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccomodationReservationId");

                    b.HasIndex("AccomodationAccId");

                    b.HasIndex("GuestUserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccomodationReservations");
                });

            modelBuilder.Entity("InitialProject.Model.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuestUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuestUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("InitialProject.Model.GuestRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccomodationReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cleanliness")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RatingExperationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleCompliance")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationReservationId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("GuestRatings");
                });

            modelBuilder.Entity("InitialProject.Model.OwnerReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccomodationReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cleanliness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerFairness")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationReservationId");

                    b.ToTable("OwnerReviews");
                });

            modelBuilder.Entity("InitialProject.Model.ReservationReschedulingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Achievable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NewEndingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NewStartingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservationAccomodationReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReservationAccomodationReservationId");

                    b.ToTable("ReservationReschedulingRequests");
                });

            modelBuilder.Entity("InitialProject.Model.TourImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourImages");
                });

            modelBuilder.Entity("InitialProject.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("WebApi.Entities.Checkpoint", b =>
                {
                    b.Property<int>("CheckpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("CheckpointId");

                    b.HasIndex("TourId");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("WebApi.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WebApi.Entities.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuideUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("TourId");

                    b.HasIndex("GuideUserId");

                    b.HasIndex("LocationId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("InitialProject.Model.Guest", b =>
                {
                    b.HasBaseType("InitialProject.Model.User");

                    b.HasDiscriminator().HasValue("Guest");
                });

            modelBuilder.Entity("InitialProject.Model.Guide", b =>
                {
                    b.HasBaseType("InitialProject.Model.User");

                    b.HasDiscriminator().HasValue("Guide");
                });

            modelBuilder.Entity("InitialProject.Model.Owner", b =>
                {
                    b.HasBaseType("InitialProject.Model.User");

                    b.HasDiscriminator().HasValue("Owner");
                });

            modelBuilder.Entity("InitialProject.Model.Tourist", b =>
                {
                    b.HasBaseType("InitialProject.Model.User");

                    b.Property<int?>("CheckpointId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("TourId");

                    b.HasDiscriminator().HasValue("Tourist");
                });

            modelBuilder.Entity("InitialProject.Model.Accomodation", b =>
                {
                    b.HasOne("InitialProject.Model.AccomodationReservation", null)
                        .WithMany("Accomodations")
                        .HasForeignKey("AccomodationReservationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InitialProject.Model.Guest", null)
                        .WithMany("Accomodations")
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Entities.Location", null)
                        .WithMany("Accomodations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InitialProject.Model.Owner", null)
                        .WithMany("Accomodations")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InitialProject.Model.AccomodationImage", b =>
                {
                    b.HasOne("InitialProject.Model.Accomodation", null)
                        .WithMany("Images")
                        .HasForeignKey("AccomodationAccId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InitialProject.Model.AccomodationReservation", b =>
                {
                    b.HasOne("InitialProject.Model.Accomodation", null)
                        .WithMany("AccomodationReservations")
                        .HasForeignKey("AccomodationAccId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InitialProject.Model.Guest", null)
                        .WithMany("AccomodationReservations")
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InitialProject.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InitialProject.Model.Comment", b =>
                {
                    b.HasOne("InitialProject.Model.Guest", null)
                        .WithMany("Comments")
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InitialProject.Model.GuestRating", b =>
                {
                    b.HasOne("InitialProject.Model.AccomodationReservation", "AccomodationReservation")
                        .WithMany()
                        .HasForeignKey("AccomodationReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InitialProject.Model.Owner", null)
                        .WithMany("GuestRatings")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AccomodationReservation");
                });

            modelBuilder.Entity("InitialProject.Model.OwnerReview", b =>
                {
                    b.HasOne("InitialProject.Model.AccomodationReservation", "AccomodationReservation")
                        .WithMany()
                        .HasForeignKey("AccomodationReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationReservation");
                });

            modelBuilder.Entity("InitialProject.Model.ReservationReschedulingRequest", b =>
                {
                    b.HasOne("InitialProject.Model.AccomodationReservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationAccomodationReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("InitialProject.Model.TourImages", b =>
                {
                    b.HasOne("WebApi.Entities.Tour", null)
                        .WithMany("Images")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Entities.Checkpoint", b =>
                {
                    b.HasOne("WebApi.Entities.Tour", null)
                        .WithMany("Checkpoints")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Entities.Tour", b =>
                {
                    b.HasOne("InitialProject.Model.Guide", null)
                        .WithMany("Tours")
                        .HasForeignKey("GuideUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Entities.Location", null)
                        .WithMany("Tours")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InitialProject.Model.Tourist", b =>
                {
                    b.HasOne("WebApi.Entities.Checkpoint", null)
                        .WithMany("Tourists")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Entities.Tour", null)
                        .WithMany("Tourists")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InitialProject.Model.Accomodation", b =>
                {
                    b.Navigation("AccomodationReservations");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("InitialProject.Model.AccomodationReservation", b =>
                {
                    b.Navigation("Accomodations");
                });

            modelBuilder.Entity("WebApi.Entities.Checkpoint", b =>
                {
                    b.Navigation("Tourists");
                });

            modelBuilder.Entity("WebApi.Entities.Location", b =>
                {
                    b.Navigation("Accomodations");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("WebApi.Entities.Tour", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("Images");

                    b.Navigation("Tourists");
                });

            modelBuilder.Entity("InitialProject.Model.Guest", b =>
                {
                    b.Navigation("AccomodationReservations");

                    b.Navigation("Accomodations");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("InitialProject.Model.Guide", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("InitialProject.Model.Owner", b =>
                {
                    b.Navigation("Accomodations");

                    b.Navigation("GuestRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
